### ISSUE TITLE
Erro in webapp

### ISSUE THREAD

**Issue by pimdewit01** [dreamhouseapp/dreamhouse-web-app#6]
Hi James, i installed app and configured Heroku Connect. Still i get the following error in the browser when starting the app (url = https://dreamhouse-web-app-einstein.herokuapp.com/)

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details._

**Comment by jamesward** [comment]
Can you check the app logs and see what the error is?

**Comment by pimdewit01** [comment]
2017-05-01T15:07:34.829354+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=dreamhouse-web-app-einstein.herokuapp.com request_id=5fc0ca3a-cf23-4292-b0a1-1f305a29b96c fwd="62.17.146.144" dyno= connect= service= status=503 bytes= protocol=https

**Comment by jamesward** [comment]
There should be more details in the logs about what went wrong.  But you might need to restart the app to see it.

**Comment by pimdewit01** [comment]
2017-05-02T08:20:51.044000+00:00 heroku[web.1]: State changed from starting to crashed
2017-05-02T08:20:51.030617+00:00 heroku[web.1]: Process exited with status 1
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-05-02T08:20:50.882628+00:00 app[web.1]: npm ERR!     node server
2017-05-02T08:20:50.882826+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-05-02T08:20:50.886069+00:00 app[web.1]: npm ERR!     npm bugs dreamhouse-web-app
2017-05-02T08:20:50.886906+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-05-02T08:20:50.887452+00:00 app[web.1]: npm ERR!     npm owner ls dreamhouse-web-app
2017-05-02T08:20:50.894108+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-05-02T08:20:50.909802+00:00 app[web.1]: 
2017-05-02T08:20:50.910138+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-05-02T08:20:50.910290+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-05-02T08:20:51.044000+00:00 heroku[web.1]: State changed from starting to crashed
2017-05-02T08:20:51.030617+00:00 heroku[web.1]: Process exited with status 1
2017-05-02T08:21:49.755750+00:00 heroku[web.1]: State changed from crashed to starting
2017-05-02T08:22:17.507299+00:00 heroku[web.1]: Restarting
2017-05-02T08:22:21.974151+00:00 heroku[web.1]: Starting process with command `npm start`
2017-05-02T08:22:24.668321+00:00 heroku[web.1]: Starting process with command `npm start`
2017-05-02T08:22:25.811870+00:00 app[web.1]: 
2017-05-02T08:22:25.811886+00:00 app[web.1]: > dreamhouse-web-app@ start /app
2017-05-02T08:22:25.811887+00:00 app[web.1]: > node server
2017-05-02T08:22:25.811887+00:00 app[web.1]: 
2017-05-02T08:22:26.422887+00:00 app[web.1]: Listening at: http://localhost:26354
2017-05-02T08:22:26.523618+00:00 app[web.1]: /app/server.js:51
2017-05-02T08:22:26.535651+00:00 app[web.1]:     callback(data.rows);
2017-05-02T08:22:26.535680+00:00 app[web.1]:                  ^
2017-05-02T08:22:26.535693+00:00 app[web.1]: 
2017-05-02T08:22:26.535707+00:00 app[web.1]: TypeError: Cannot read property 'rows' of undefined
2017-05-02T08:22:26.535709+00:00 app[web.1]:     at .callback (/app/server.js:51:18)
2017-05-02T08:22:26.535710+00:00 app[web.1]:     at Query.handleError (/app/node_modules/pg/lib/query.js:106:17)
2017-05-02T08:22:26.535711+00:00 app[web.1]:     at .<anonymous> (/app/node_modules/pg/lib/client.js:171:26)
2017-05-02T08:22:26.535711+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-05-02T08:22:26.535712+00:00 app[web.1]:     at emit (events.js:188:7)
2017-05-02T08:22:26.535713+00:00 app[web.1]:     at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:109:12)
2017-05-02T08:22:26.535714+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-05-02T08:22:26.535714+00:00 app[web.1]:     at TLSSocket.emit (events.js:188:7)
2017-05-02T08:22:26.535715+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:172:18)
2017-05-02T08:22:26.535727+00:00 app[web.1]:     at TLSSocket.Readable.push (_stream_readable.js:130:10)
2017-05-02T08:22:26.577006+00:00 app[web.1]: 
2017-05-02T08:22:26.617934+00:00 app[web.1]: npm ERR! Linux 3.13.0-112-generic
2017-05-02T08:22:26.618444+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-05-02T08:22:26.618753+00:00 app[web.1]: npm ERR! node v6.1.0
2017-05-02T08:22:26.619318+00:00 app[web.1]: npm ERR! npm  v3.8.6
2017-05-02T08:22:26.619603+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-05-02T08:22:26.619828+00:00 app[web.1]: npm ERR! dreamhouse-web-app@ start: `node server`
2017-05-02T08:22:26.620040+00:00 app[web.1]: npm ERR! Exit status 1
2017-05-02T08:22:26.620259+00:00 app[web.1]: npm ERR! 
2017-05-02T08:22:26.620490+00:00 app[web.1]: npm ERR! Failed at the dreamhouse-web-app@ start script 'node server'.
2017-05-02T08:22:26.620706+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-05-02T08:22:26.621337+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the dreamhouse-web-app package,
2017-05-02T08:22:26.621544+00:00 app[web.1]: npm ERR! not with npm itself.
2017-05-02T08:22:26.621750+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-05-02T08:22:26.621964+00:00 app[web.1]: npm ERR!     node server
2017-05-02T08:22:26.622159+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-05-02T08:22:26.622392+00:00 app[web.1]: npm ERR!     npm bugs dreamhouse-web-app
2017-05-02T08:22:26.622597+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-05-02T08:22:26.622796+00:00 app[web.1]: npm ERR!     npm owner ls dreamhouse-web-app
2017-05-02T08:22:26.622990+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-05-02T08:22:26.628740+00:00 app[web.1]: 
2017-05-02T08:22:26.629074+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-05-02T08:22:26.629268+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-05-02T08:22:26.742329+00:00 heroku[web.1]: Process exited with status 1
2017-05-02T08:22:28.313597+00:00 app[web.1]: 
2017-05-02T08:22:28.313621+00:00 app[web.1]: > dreamhouse-web-app@ start /app
2017-05-02T08:22:28.313623+00:00 app[web.1]: > node server
2017-05-02T08:22:28.313623+00:00 app[web.1]: 
2017-05-02T08:22:28.947626+00:00 heroku[web.1]: State changed from starting to up
2017-05-02T08:22:28.858540+00:00 app[web.1]: Listening at: http://localhost:16027
2017-05-02T08:22:28.951693+00:00 app[web.1]: /app/server.js:51
2017-05-02T08:22:28.951696+00:00 app[web.1]:     callback(data.rows);
2017-05-02T08:22:28.951697+00:00 app[web.1]:                  ^
2017-05-02T08:22:28.951698+00:00 app[web.1]: 
2017-05-02T08:22:28.951699+00:00 app[web.1]: TypeError: Cannot read property 'rows' of undefined
2017-05-02T08:22:28.951699+00:00 app[web.1]:     at .callback (/app/server.js:51:18)
2017-05-02T08:22:28.951700+00:00 app[web.1]:     at Query.handleError (/app/node_modules/pg/lib/query.js:106:17)
2017-05-02T08:22:28.951701+00:00 app[web.1]:     at .<anonymous> (/app/node_modules/pg/lib/client.js:171:26)
2017-05-02T08:22:28.951701+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-05-02T08:22:28.951702+00:00 app[web.1]:     at emit (events.js:188:7)
2017-05-02T08:22:28.951703+00:00 app[web.1]:     at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:109:12)
2017-05-02T08:22:28.951703+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-05-02T08:22:28.951704+00:00 app[web.1]:     at TLSSocket.emit (events.js:188:7)
2017-05-02T08:22:28.951705+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:172:18)
2017-05-02T08:22:28.951710+00:00 app[web.1]:     at TLSSocket.Readable.push (_stream_readable.js:130:10)
2017-05-02T08:22:28.962673+00:00 app[web.1]: 
2017-05-02T08:22:28.987313+00:00 app[web.1]: npm ERR! Linux 3.13.0-112-generic
2017-05-02T08:22:28.987935+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-05-02T08:22:28.988326+00:00 app[web.1]: npm ERR! node v6.1.0
2017-05-02T08:22:28.992021+00:00 app[web.1]: npm ERR! npm  v3.8.6
2017-05-02T08:22:28.992964+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-05-02T08:22:28.993263+00:00 app[web.1]: npm ERR! dreamhouse-web-app@ start: `node server`
2017-05-02T08:22:28.993558+00:00 app[web.1]: npm ERR! Exit status 1
2017-05-02T08:22:28.993830+00:00 app[web.1]: npm ERR! 
2017-05-02T08:22:28.994083+00:00 app[web.1]: npm ERR! Failed at the dreamhouse-web-app@ start script 'node server'.
2017-05-02T08:22:28.995120+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-05-02T08:22:28.995604+00:00 app[web.1]: npm
 ERR! If you do, this is most likely a problem with the dreamhouse-web-app package,
2017-05-02T08:22:28.995926+00:00 app[web.1]: npm ERR! not with npm itself.
2017-05-02T08:22:28.996140+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-05-02T08:22:28.996386+00:00 app[web.1]: npm ERR!     node server
2017-05-02T08:22:28.996605+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-05-02T08:22:28.996820+00:00 app[web.1]: npm ERR!     npm bugs dreamhouse-web-app
2017-05-02T08:22:28.997074+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-05-02T08:22:28.997318+00:00 app[web.1]: npm ERR!     npm owner ls dreamhouse-web-app
2017-05-02T08:22:28.997534+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-05-02T08:22:29.003218+00:00 app[web.1]: 
2017-05-02T08:22:29.005286+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-05-02T08:22:29.006515+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-05-02T08:22:28.996386+00:00 app[web.1]: npm ERR!     node server
2017-05-02T08:22:28.996605+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-05-02T08:22:28.996820+00:00 app[web.1]: npm ERR!     npm bugs dreamhouse-web-app
2017-05-02T08:22:28.997074+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-05-02T08:22:28.997318+00:00 app[web.1]: npm ERR!     npm owner ls dreamhouse-web-app
2017-05-02T08:22:28.997534+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-05-02T08:22:29.003218+00:00 app[web.1]: 
2017-05-02T08:22:29.005286+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-05-02T08:22:29.006515+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-05-02T08:22:29.130911+00:00 heroku[web.1]: State changed from up to crashed
2017-05-02T08:22:29.121017+00:00 heroku[web.1]: Process exited with status 1
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-05-02T08:22:28.996386+00:00 app[web.1]: npm ERR!     node server
2017-05-02T08:22:28.996605+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-05-02T08:22:28.996820+00:00 app[web.1]: npm ERR!     npm bugs dreamhouse-web-app
2017-05-02T08:22:28.997074+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-05-02T08:22:28.997318+00:00 app[web.1]: npm ERR!     npm owner ls dreamhouse-web-app
2017-05-02T08:22:28.997534+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-05-02T08:22:29.003218+00:00 app[web.1]: 
2017-05-02T08:22:29.005286+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-05-02T08:22:29.006515+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-05-02T08:22:29.130911+00:00 heroku[web.1]: State changed from up to crashed
2017-05-02T08:22:29.121017+00:00 heroku[web.1]: Process exited with status 1
 Autoscroll with output
heroku.com Blogs Careers Documenta

**Comment by jamesward** [comment]
I think this might be a race condition.  But before I dig deeper can you confirm that `SELECT * FROM salesforce.broker__c;` works?  You can run this query with `heroku psql -a HEROKU_APP_NAME`

**Comment by dstdia** [comment]
@pimdewit01 did you manage to resolve the issue? I got the same thing here, same error, and querying the salesforce.broker__c table works fine.
